blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  resources :comments
  resources :posts
  get 'home/index'

  root 'home#index' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  # GET /comments/1/edit
  def edit
    authenticate_user(@comment.user_id)
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id] 
    @comment.user_id = cookies[:username]

    @post = Post.find(@comment.post_id)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    authenticate_user(@comment.user_id)
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    authenticate_user(@comment.user_id)
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :body)
    end

    def authenticate_user(user_id)
      if (cookies[:admin].nil? || !cookies[:admin]) && user_id != cookies[:username]
      then redirect_to home_index_path
      end
    end

end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.text_field :post_id %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= form_for @comment do |comment_form| %>
  <p> Comment:</br> <%= comment_form.text_field :body %> </p>
  <%= hidden_field_tag(:post_id, @comment.post_id) %>
  <%= comment_form.submit :Comment %>
<% end %>
<% if @comment.errors.any? %>
  <ul class="Comment_Errors">
    <% for message_error in @comment.errors.full_messages %>
    <li>* <%= message_error %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Cancel', @comment %>

blog/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_for @comment do |comment_form| %>
  <p> Comment:</br> <%= comment_form.text_field :body %> </p>
  <%= hidden_field_tag(:post_id, @comment.post_id) %>
  <%= comment_form.submit :Comment %>
<% end %>
<% if @comment.errors.any? %>
  <ul class="Comment_Errors">
    <% for message_error in @comment.errors.full_messages %>
    <li>* <%= message_error %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Back', Post.find(@comment.post_id) %>

blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Added by:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.body %>
</p>

<% if cookies[:admin] || @comment.user_id == cookies[:username] %>
<% then %>
<%= link_to 'Edit', edit_comment_path(@comment) %> 
<%= link_to 'Back', Post.find(@comment.post_id) %>

<% end %>