blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users
  resources :comments
  resources :posts
  get 'home/index'

  root 'home#index' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

blog/app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :content
  validates_length_of :title, :minimum => 5
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = (Comment.where(post_id: @post.id)).sort_by {|c| c.created_at}
  end

  # GET /posts/new
  def new
    authenticate_admin()
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authenticate_admin()
  end

  # POST /posts
  # POST /posts.json
  def create
    authenticate_admin()
    @post = Post.new(post_params)
   
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authenticate_admin()
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authenticate_admin()
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def authenticate_admin
      if cookies[:admin].nil? || !cookies[:admin]
      then redirect_to home_index_path
      end
    end
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>

	<% if (!cookies[:admin].nil?) && cookies[:admin] %>
	<% then %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if (!cookies[:admin].nil?) && cookies[:admin] %>
<% then %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<% if cookies[:username].nil? %>
<% then %>
  <h1>You must be logged in to add comments</h1>
  <%= link_to "Register", new_user_path %>
  <%= link_to "Login", login_path %>
<% else %>
  <h4>logged as</h4>
  <%= cookies[:username] %>
  <%= link_to "Log out", logout_path, method: "delete" %>
  <%= link_to "Comment", new_comment_path(:post_id => @post.id) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Time added</th>
      <th>User</th>
      <th>Comment</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
	<td><%= comment.created_at %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>